Pickering	Oakville	0	2
Tecumseh	Whitby	0	2
Rush	Pickering	2	8
Scrosoppi	Oakville	1	0
Tecumseh	Hamilton	0	1
Burlington	UMSC	1	6
Whitby	UMSC	0	1
Burlington	Tecumseh	0	2
Hamilton	Scrosoppi	1	0
Oakville	Rush	1	1
Scrosoppi	Pickering	4	2
Whitby	Burlington	3	2
UMSC	Hamilton	1	4
Tecumseh	Rush	2	4
Burlington	Hamilton	0	1
Whitby	Oakville	1	0
UMSC	Pickering	0	1


In [12]:
pickering = 0
oakville = 1
tecumseh = 2
whitby = 3
rush = 4
scrosoppi = 5
hamilton = 6
burlington = 7
umsc = 8

matches = [
  [oakville, pickering, 2],
  [whitby, tecumseh, 2],
  [pickering, rush, 6],
  [scrosoppi, oakville, 1],
  [hamilton, tecumseh, 1],
  [umsc, burlington, 5],
  [umsc, whitby, 1],
  [tecumseh, burlington, 2],
  [hamilton, scrosoppi, 1],
  [oakville, rush, 0],
  [scrosoppi, pickering, 2],
  [whitby, burlington, 1],
  [hamilton, umsc, 3],
  [rush, tecumseh, 2],
  [hamilton, burlington, 1],
  [whitby, oakville, 1],
  [pickering, umsc, 1]
]

In [13]:
import numpy as np

def buildGamesMatrix(games, num_teams):
  M = np.zeros([len(games), num_teams])
  row = 0
  for g in games:
    M[row, g[0]] = 1
    M[row, g[1]] = -1
    row += 1
  return M

M = buildGamesMatrix(matches,9)
print(M)

[[-1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  1.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0. -1.  1.  0.  0.]
 [ 0.  1.  0.  0. -1.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0. -1.]
 [ 0.  0. -1.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0. -1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0. -1.]]


In [14]:
def buildOutcomes(games):
  E = np.zeros([len(games)])
  row = 0
  for g in games:
    E[row] = g[2]
    row += 1
  return E

E = buildOutcomes(matches)
print(E)

[2. 2. 6. 1. 1. 5. 1. 2. 1. 0. 2. 1. 3. 2. 1. 1. 1.]


In [15]:
bh = np.linalg.lstsq(M,E)[0]

print(bh)

[ 1.0210417   0.33568345 -1.2827786   0.12286167 -1.30868448  1.50751489
  1.16581953 -2.11111111  0.54965295]
